#!/bin/bash

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Configuration variables
DEPLOY_USER="sigmagit"
DEPLOY_DIR="/home/$DEPLOY_USER"
APP_DIR="$DEPLOY_DIR/sigmagit"
STORAGE_DIR="$DEPLOY_DIR/sigmagit-storage"
LOGS_DIR="$DEPLOY_DIR/logs"
BACKUP_DIR="$DEPLOY_DIR/backups"
SCRIPTS_DIR="$DEPLOY_DIR/scripts"
COMPOSE_FILES="-f docker-compose.yml -f docker-compose.prod.yml"

WEB_DOMAIN=""
DOCS_DOMAIN=""
GIT_REPO=""
POSTGRES_PASSWORD=""
BETTER_AUTH_SECRET=""
RESEND_API_KEY=""
SMTP_HOST=""
SMTP_PORT=""
SMTP_USER=""
SMTP_PASSWORD=""
DISCORD_BOT_TOKEN=""
DISCORD_CLIENT_ID=""
ENABLE_DISCORD="false"

log_info() {
  echo -e "${GREEN}[INFO]${NC} $1"
}

log_warn() {
  echo -e "${YELLOW}[WARN]${NC} $1"
}

log_error() {
  echo -e "${RED}[ERROR]${NC} $1"
}

check_root() {
  if [[ $EUID -ne 0 ]]; then
    log_error "This script must be run as root or with sudo"
    exit 1
  fi
}

check_ubuntu_debian() {
  if ! command -v apt-get &>/dev/null; then
    log_error "This script is designed for Ubuntu/Debian systems only"
    exit 1
  fi
}

compose_cmd() {
  su - "$DEPLOY_USER" -c "cd $APP_DIR && docker compose $COMPOSE_FILES $*"
}

prompt_input() {
  local prompt_text="$1"
  local default_value="$2"
  local var_name="$3"

  if [ -n "$default_value" ]; then
    read -p "$prompt_text [$default_value]: " input
    input=${input:-$default_value}
  else
    read -p "$prompt_text: " input
  fi

  eval "$var_name='$input'"
}

prompt_password() {
  local prompt_text="$1"
  local var_name="$2"

  while true; do
    read -s -p "$prompt_text: " input1
    echo
    read -s -p "Confirm $prompt_text: " input2
    echo

    if [ "$input1" == "$input2" ]; then
      eval "$var_name='$input1'"
      break
    else
      log_error "Passwords do not match. Please try again."
    fi
  done
}

update_system() {
  log_info "Updating system packages..."
  apt-get update && apt-get upgrade -y
}

create_user() {
  log_info "Creating deployment user..."

  if id "$DEPLOY_USER" &>/dev/null; then
    log_warn "User $DEPLOY_USER already exists. Skipping..."
  else
    adduser --gecos "" --disabled-password "$DEPLOY_USER"
    usermod -aG sudo "$DEPLOY_USER"
    echo "$DEPLOY_USER ALL=(ALL) NOPASSWD:/usr/bin/docker, /usr/bin/docker compose, /usr/bin/systemctl" > /etc/sudoers.d/$DEPLOY_USER
    chmod 440 /etc/sudoers.d/$DEPLOY_USER
    log_info "User $DEPLOY_USER created successfully"
  fi

  mkdir -p "$LOGS_DIR" "$BACKUP_DIR" "$SCRIPTS_DIR" "$STORAGE_DIR"
  chown -R "$DEPLOY_USER:$DEPLOY_USER" "$DEPLOY_DIR"
}

install_docker() {
  log_info "Installing Docker and Docker Compose..."

  if command -v docker &>/dev/null && docker compose version &>/dev/null; then
    log_warn "Docker is already installed. Skipping..."
  else
    curl -fsSL https://get.docker.com | sh
    log_info "Docker installed successfully"
  fi

  usermod -aG docker "$DEPLOY_USER"
  systemctl enable docker
  systemctl start docker

  docker compose version
}

clone_repository() {
  log_info "Cloning repository..."

  if [ -d "$APP_DIR" ]; then
    log_warn "Repository already exists. Pulling latest changes..."
    su - "$DEPLOY_USER" -c "cd $APP_DIR && git pull origin main"
  else
    su - "$DEPLOY_USER" -c "git clone $GIT_REPO $APP_DIR"
    log_info "Repository cloned successfully"
  fi
}

create_compose_override() {
  log_info "Creating docker-compose.prod.yml..."

  cat > "$APP_DIR/docker-compose.prod.yml" << EOF
# Generated by deploy.sh — production overrides for Docker Compose
services:
  api:
    volumes:
      - $STORAGE_DIR:/data/repos
    environment:
      STORAGE_TYPE: local
      STORAGE_LOCAL_PATH: /data/repos

  migrate:
    profiles: [tools]
    image: oven/bun:1.3.5
    working_dir: /app
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql://sigmagit:\${POSTGRES_PASSWORD}@postgres:5432/sigmagit
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - sigmagit
    command: ["sh", "-c", "bun install && cd packages/db && bun run db:migrate"]

  discord-bot:
    profiles: [discord]
    build:
      context: .
      dockerfile: apps/discord-bot/Dockerfile
    restart: unless-stopped
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql://sigmagit:\${POSTGRES_PASSWORD}@postgres:5432/sigmagit
      REDIS_SESSION_URL: redis://redis-session:6379
      REDIS_CACHE_URL: redis://redis-cache:6379
    depends_on:
      postgres:
        condition: service_healthy
      api:
        condition: service_healthy
    networks:
      - sigmagit
EOF

  chown "$DEPLOY_USER:$DEPLOY_USER" "$APP_DIR/docker-compose.prod.yml"
  log_info "docker-compose.prod.yml created"
}

create_env_file() {
  log_info "Creating environment file..."

  cat > "$APP_DIR/.env" << EOF
# Application
NODE_ENV=production
WEB_URL=https://$WEB_DOMAIN
API_URL=https://$WEB_DOMAIN
VITE_API_URL=https://$WEB_DOMAIN
TRUST_PROXY=true

# Docker Compose
POSTGRES_PASSWORD=$POSTGRES_PASSWORD

# Database (used by migrate profile and host tooling)
DATABASE_URL=postgresql://sigmagit:$POSTGRES_PASSWORD@postgres:5432/sigmagit

# Storage (local volume mounted into api container)
STORAGE_TYPE=local
STORAGE_LOCAL_PATH=/data/repos

# Auth
BETTER_AUTH_SECRET=$BETTER_AUTH_SECRET
BETTER_AUTH_URL=https://$WEB_DOMAIN

# Email
EMAIL_PROVIDER=resend
RESEND_API_KEY=$RESEND_API_KEY
SMTP_HOST=$SMTP_HOST
SMTP_PORT=$SMTP_PORT
SMTP_USER=$SMTP_USER
SMTP_PASS=$SMTP_PASSWORD
EMAIL_FROM=Sigmagit <noreply@$WEB_DOMAIN>

# Discord (optional — enable with: docker compose --profile discord up -d)
DISCORD_BOT_TOKEN=$DISCORD_BOT_TOKEN
DISCORD_CLIENT_ID=$DISCORD_CLIENT_ID
EOF

  chmod 600 "$APP_DIR/.env"
  chown "$DEPLOY_USER:$DEPLOY_USER" "$APP_DIR/.env"
  log_info "Environment file created successfully"
}

configure_caddyfile() {
  log_info "Configuring Caddyfile for $WEB_DOMAIN..."

  if [ -f "$APP_DIR/Caddyfile" ] && [ ! -f "$APP_DIR/Caddyfile.bak" ]; then
    cp "$APP_DIR/Caddyfile" "$APP_DIR/Caddyfile.bak"
  fi

  cat > "$APP_DIR/Caddyfile" << EOF
{
    email admin@$WEB_DOMAIN

    servers {
        client_ip_headers X-Forwarded-For X-Real-IP
    }
}

$WEB_DOMAIN {
    handle /health {
        reverse_proxy {\$API_UPSTREAM:localhost:3001}
    }

    handle /api/health {
        reverse_proxy {\$API_UPSTREAM:localhost:3001}
    }

    handle /ws {
        reverse_proxy {\$API_UPSTREAM:localhost:3001}
    }

    handle /v2/* {
        request_body {
            max_size 500MB
        }
        reverse_proxy {\$API_UPSTREAM:localhost:3001} {
            flush_interval -1
            transport http {
                read_timeout 600s
                write_timeout 600s
            }
        }
    }

    handle /file/* {
        reverse_proxy {\$API_UPSTREAM:localhost:3001}
    }

    @git path_regexp git ^/[^/]+/[^/]+\\.git(/.*)?\$
    handle @git {
        request_body {
            max_size 100MB
        }
        reverse_proxy {\$API_UPSTREAM:localhost:3001} {
            flush_interval -1
            transport http {
                read_timeout 600s
                write_timeout 600s
            }
        }
    }

    handle /api/* {
        reverse_proxy {\$API_UPSTREAM:localhost:3001}
    }

    handle {
        reverse_proxy {\$WEB_UPSTREAM:localhost:3000}
    }

    @compressible not path /v2/* /file/* /ws
    @compressible not path_regexp git ^/[^/]+/[^/]+\\.git(/.*)?\$
    encode @compressible zstd gzip

    log {
        output stdout
    }
}
EOF

  if [ -n "$DOCS_DOMAIN" ]; then
    cat >> "$APP_DIR/Caddyfile" << EOF

$DOCS_DOMAIN {
    reverse_proxy {\$DOCS_UPSTREAM:localhost:3003}

    encode zstd gzip

    log {
        output stdout
    }
}
EOF
  fi

  chown "$DEPLOY_USER:$DEPLOY_USER" "$APP_DIR/Caddyfile"
  log_info "Caddyfile configured"
}

build_and_start() {
  log_info "Building and starting services with Docker Compose..."

  compose_cmd "build"

  if [ "$ENABLE_DISCORD" = "true" ]; then
    compose_cmd "--profile discord up -d"
  else
    compose_cmd "up -d"
  fi

  log_info "Services started"
}

run_migrations() {
  log_info "Running database migrations..."
  compose_cmd "--profile tools run --rm migrate"
  log_info "Migrations completed"
}

wait_for_healthy() {
  log_info "Waiting for PostgreSQL to become ready..."
  local retries=30
  while [ $retries -gt 0 ]; do
    if compose_cmd "exec -T postgres pg_isready -U sigmagit -d sigmagit" >/dev/null 2>&1; then
      log_info "PostgreSQL is ready"
      return 0
    fi
    retries=$((retries - 1))
    sleep 2
  done
  log_warn "Timed out waiting for PostgreSQL — check: cd $APP_DIR && docker compose $COMPOSE_FILES ps"
}

configure_firewall() {
  log_info "Configuring firewall..."

  if ! command -v ufw &>/dev/null; then
    apt-get install -y ufw
  fi

  ufw allow 22/tcp
  ufw allow 80/tcp
  ufw allow 443/tcp
  echo "y" | ufw enable

  log_info "Firewall configured"
}

create_backup_script() {
  log_info "Creating backup script..."

  cat > "$SCRIPTS_DIR/backup.sh" << EOF
#!/bin/bash
set -e
BACKUP_DIR="$BACKUP_DIR"
DATE=\$(date +%Y%m%d_%H%M%S)
BACKUP_FILE="\$BACKUP_DIR/sigmagit_\$DATE.sql"

mkdir -p "\$BACKUP_DIR"

cd "$APP_DIR"
docker compose $COMPOSE_FILES exec -T postgres \\
  pg_dump -U sigmagit sigmagit > "\$BACKUP_FILE"

gzip "\$BACKUP_FILE"
find "\$BACKUP_DIR" -name "*.sql.gz" -mtime +7 -delete

echo "Backup completed: \${BACKUP_FILE}.gz"
EOF

  chmod +x "$SCRIPTS_DIR/backup.sh"
  chown "$DEPLOY_USER:$DEPLOY_USER" "$SCRIPTS_DIR/backup.sh"

  (crontab -l -u "$DEPLOY_USER" 2>/dev/null || true; echo "0 2 * * * $SCRIPTS_DIR/backup.sh >> $LOGS_DIR/backup.log 2>&1") | crontab -u "$DEPLOY_USER" -

  log_info "Backup script created and scheduled"
}

create_update_script() {
  log_info "Creating update script..."

  cat > "$SCRIPTS_DIR/update.sh" << EOF
#!/bin/bash
set -e
cd "$APP_DIR"
git pull origin main
docker compose $COMPOSE_FILES build
docker compose $COMPOSE_FILES up -d
docker compose $COMPOSE_FILES --profile tools run --rm migrate
echo "Update complete"
EOF

  chmod +x "$SCRIPTS_DIR/update.sh"
  chown "$DEPLOY_USER:$DEPLOY_USER" "$SCRIPTS_DIR/update.sh"
  log_info "Update script created at $SCRIPTS_DIR/update.sh"
}

print_summary() {
  log_info "Deployment completed successfully!"
  echo
  echo "=== Summary ==="
  echo "Web URL: https://$WEB_DOMAIN"
  echo "API URL: https://$WEB_DOMAIN/api"
  if [ -n "$DOCS_DOMAIN" ]; then
    echo "Docs URL: https://$DOCS_DOMAIN"
  fi
  echo "User: $DEPLOY_USER"
  echo "App Directory: $APP_DIR"
  echo "Storage Directory: $STORAGE_DIR"
  echo
  echo "=== Docker Compose Commands ==="
  echo "Status:  cd $APP_DIR && docker compose $COMPOSE_FILES ps"
  echo "Logs:    cd $APP_DIR && docker compose $COMPOSE_FILES logs -f"
  echo "Restart: cd $APP_DIR && docker compose $COMPOSE_FILES restart"
  echo "Update:  $SCRIPTS_DIR/update.sh"
  echo "Backup:  $SCRIPTS_DIR/backup.sh"
  if [ "$ENABLE_DISCORD" = "true" ]; then
    echo "Discord bot is enabled (discord profile)"
  else
    echo "Discord bot disabled — set token and run: docker compose $COMPOSE_FILES --profile discord up -d"
  fi
  echo
}

main() {
  echo "==================================="
  echo "  Sigmagit Docker Compose Deploy  "
  echo "==================================="
  echo

  check_root
  check_ubuntu_debian

  log_info "Please provide the following configuration:"
  prompt_input "Git repository URL" "" GIT_REPO
  prompt_input "Primary domain (e.g., sigmagit.com)" "" WEB_DOMAIN
  prompt_input "Docs domain (optional, press Enter to skip)" "" DOCS_DOMAIN
  prompt_password "PostgreSQL password" POSTGRES_PASSWORD
  prompt_input "Better Auth Secret (min 32 chars)" "" BETTER_AUTH_SECRET
  prompt_input "Resend API Key (optional)" "" RESEND_API_KEY
  prompt_input "SMTP Host (optional)" "smtp.gmail.com" SMTP_HOST
  prompt_input "SMTP Port (optional)" "587" SMTP_PORT
  prompt_input "SMTP User (optional)" "" SMTP_USER
  prompt_input "SMTP Password (optional)" "" SMTP_PASSWORD
  prompt_input "Discord Bot Token (optional)" "" DISCORD_BOT_TOKEN
  prompt_input "Discord Client ID (optional)" "" DISCORD_CLIENT_ID

  if [ -n "$DISCORD_BOT_TOKEN" ] && [ -n "$DISCORD_CLIENT_ID" ]; then
    ENABLE_DISCORD="true"
  fi

  echo
  log_warn "Starting deployment process..."
  echo

  update_system
  create_user
  install_docker
  clone_repository
  create_compose_override
  create_env_file
  configure_caddyfile
  build_and_start
  wait_for_healthy
  run_migrations
  configure_firewall
  create_backup_script
  create_update_script
  print_summary
}

main
